version: "3.8"
services:
  producer:
    build: .
    image: cybre/google-chat-service
    container_name: producer
    command: /app/producer
    environment:
      - PORT=3000
      - RABBITMQ_HOST=rabbitmq:5672
    ports:
      - "3000:3000"
    depends_on:
      - consumer
    networks:
      - local
  consumer:
    build: .
    image: cybre/google-chat-service
    container_name: consumer
    command: /app/consumer
    env_file: .env
    environment:
      - SELENIUM_SERVER_HOST=selenium-hub:4444
      - RABBITMQ_HOST=rabbitmq:5672
    depends_on:
      - chrome
      - rabbitmq
    networks:
      - local
  chrome:
    image: selenium/node-chrome:4.1.2-20220217
    container_name: chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900:5900"
    networks:
      - local
  selenium-hub:
    image: selenium/hub:4.1.2-20220217
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - local
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - local
networks:
  local:
    driver: bridge